export const   
    GET_PRODUCT_API_REQUEST = 'GET_PRODUCT_API_REQUEST', 
    GET_PRODUCT_API = 'GET_PRODUCT_API',
    GET_PRODUCT_API_ERROR = 'GET_PRODUCT_API_ERROR',
    ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';